export enum ValidateKey {
	REQUIRED = 'required',
	EMAIL = 'invalidEmail',
	PHONE = 'invalidPhone',
	MIN_LENGTH_CUSTOM = 'minLength',
	MAX_LENGTH_CUSTOM = 'maxLength',
	HAS_LENGTH = 'hasLength',
	ONLY_DIGITS_AND_LETTERS = 'onlyDigitisAndLetters',
	HAS_NOT_UPPER_CASE = 'hasNotUpperCase',
	HAS_NOT_LOWER_CASE = 'hasNotLowerCase',
	HAS_SPACE = 'hasSpace',
	HAS_NOT_DIGIT = 'hasNotDigit',
	CONFIRM_PASSWORD_ERROR = 'confirmPasswordError',
	HAS_NOT_LENGTH = 'hasNotLength',
	CALENDAR_RANGE = 'calendarRange',
	NOT_EMPTY = 'notEmpty',
	ONLY_DIGITS = 'onlyDigits',
	FLOAT = 'float',
	MAX_VALUE = 'maxValue',
	INTEGERS_AND_DECIMALS_SUPPORTED = 'integersAndDecimalsSupported',
	NOT_NEGATIVE = 'negativeNumber',
	PASSWORD_MISMATCH = 'passwordMismatch',
}
